### ISSUE TITLE
Sphinx documentation was not build due to notebook errors

### ISSUE THREAD

**Issue by uvchik** [wind-python/windpowerlib#10]
I had a look at the sphinx documentation to check the API of a function and found out that the most actual version was build 6 month ago.

I fixed the requirements and the doctests but sphinx also checks the notebook in the docs folder.

Now we have three options

 1. Check the notebook within the pytests and switch off the sphinx test with `nbsphinx_allow_errors = True` in config.py (my preferred solution)
 2.  Leave it as it is and repair the notebook (second best solution in my opinion)
 3.  Switch off the sphinx test (bad solution)

I think the best place to test the examples is the test environment (1). If it does not work so easily we can let Sphinx (readthedocs) do the job (2). I think it is less comfortable because Sphinx/RTD can fail due to many reasons and it is not so clear. If we just switch it of we may not notice if the notebook is broken (3).

**Comment by birgits** [comment]
Thank you for noticing @uvchik! I added a notebook test. However, I would rather not ignore notebook errors when building the documentation since it is an important part of the documentation and should be noticed. In my opinion the tests should be sufficient.

**Comment by uvchik** [comment]
> However, I would rather not ignore notebook errors when building the documentation since it is an important part of the documentation and should be noticed.

Sounds reasonable and I am fine with the double check. For me the test just do not seem to work (#12)
