### ISSUE TITLE
Problems with database connection

### ISSUE THREAD

**Issue by uvchik** [wind-python/windpowerlib#108]
I improved the error message to understand the reason. Now we get the following error message:

```
ConnectionError: Database (oep) connection not successful. 
URL: http://oep.iks.cs.ovgu.de//api/v0/schema/supply/tables/wind_turbine_library/rows/?
Response: [400] 
{"reason": "Connection limit for anonymous users is exceeded. Please login to get your own connection pool."}
```

How shall we deal with it?

**Comment by Ludee** [comment]
Seems like the limit of anon connections to the OEP is exceeded. Busy day ;)

One simple solution is to include the user/token input in the code. The need to create a good template and improve the documentation for this is obvious.

You can find the API-Tutorials here:
https://openenergy-platform.org/tutorials/

Here is the party with the token:
https://openenergy-platform.org/tutorials/61201725-493f-4dd0-b9aa-6e0f6d6aa550/

**Comment by ciaradunks** [comment]
I have received the same message today for trying to get weather data from open_FRED, does this mean that I need to follow the above tutorials and sign up/get a token? Or will it work if I try another day when the limit for connections hasn't been exceeded? Thanks

**Comment by uvchik** [comment]
By now the bug is resolved but it can occur again.  We should talk about the OEP connection in general.

**Comment by uvchik** [comment]
It might have been a single event, so we may keep everything as it is until it happens again.
