### ISSUE TITLE
create_power_curve does not exist

### ISSUE THREAD

**Issue by michelrezkalla** [wind-python/windpowerlib#109]
I'm trying to create a new power curve as stated in the exmple but the create_power_curve does not exist in the windpowerlib:

import pandas as pd
from windpowerlib import WindTurbine, create_power_curve
my_data = pd.read_csv("path/to/my/data/file.csv")

my_turbine_data = {
    "nominal_power": 6e6,  # in W
    "hub_height": 115,  # in m
    "power_curve": create_power_curve(
        wind_speed=my_data["wind"], power=my_data["power"]
    ),
}

my_turbine = WindTurbine(**my_turbine2)

**Comment by uvchik** [comment]
Sorry, there was a typo in the example. I fixed it with commit: af19aca04f9

You have to pass `my_turbine_data` and not `my_turbine2`, which does not exist.

```python
import pandas as pd
from windpowerlib import WindTurbine, create_power_curve
my_data = pd.read_csv("/home/uwe/sdf.csv")

my_turbine_data = {
    "nominal_power": 6e6,  # in W
    "hub_height": 115,  # in m
    "power_curve": create_power_curve(
        wind_speed=my_data["wind"], power=my_data["power"]
    ),
}

my_turbine = WindTurbine(**my_turbine_data)
```

**Comment by uvchik** [comment]
@michelrezkalla Please close this issue if it has been solved.

**Comment by Aishwarya1602** [comment]
I am trying to make a wind power curve using my own data .
but i get the following error:
cannot import name 'create_power_curve' from 'windpowerlib'(C:\Users\XXXXXXX\anaconda3\lib\site-packages\windpowerlib\__init__.py)

**Comment by uvchik** [comment]
@Aishwarya1602 : Use `pip install https://github.com/wind-python/windpowerlib/archive/dev.zip` to install the most actual version.

The function you want to use is not part of v0.2.0!
