### ISSUE TITLE
Changing the imports to absolute imports

### ISSUE THREAD

**Issue by uvchik** [wind-python/windpowerlib#11]
I had some problems using single modules of the windpowerlib. Couldn't we use absolute imports as it is recommended in [PEP8's import section](https://www.python.org/dev/peps/pep-0008/#imports). 

> Absolute imports are recommended, as they are usually more readable and tend to be better behaved (or at least give better error messages) if the import system is incorrectly configured (such as when a directory inside a package ends up on sys.path):
> 
> import mypkg.sibling
> from mypkg import sibling
> from mypkg.sibling import example
> 
> However, explicit relative imports are an acceptable alternative to absolute imports, especially when dealing with complex package layouts where using absolute imports would be unnecessarily verbose:
> 
> from . import sibling
> from .sibling import example
> 
> Standard library code should avoid complex package layouts and always use absolute imports.
> 
> Implicit relative imports should never be used and have been removed in Python 3.

I could do that, but I do not want to cause merge conflicts. So tell me what you think about it. It is definitely not urgent.

BTW, oemof changed all imports to absolute imports with v0.2.0.

**Comment by birgits** [comment]
I could only find one relative import in the modelchain module and changed it. Does this fix your issue or is there anything else I was missing?

**Comment by uvchik** [comment]
I think it is clearer this way. Thank you @birgits :tada:
