### ISSUE TITLE
Error in running modelchain_example.py

### ISSUE THREAD

**Issue by MartaFochesato** [wind-python/windpowerlib#110]
I have tried to run the code modelchain_example.py present in the example folder, but I got the following error:

Traceback (most recent call last):
  File "C:\Users\marta\PycharmProjects\Renewables\WindPowerForecast\WindEnergy_calculator.py", line 329, in <module>
    my_wind_turbine_model = ModelChain(my_wind_turbine, **modelchain_data).run_model(weather)
  File "C:\Users\marta\PycharmProjects\Renewables\WindPowerForecast\venv\lib\site-packages\windpowerlib\modelchain.py", line 443, in run_model
    wind_speed_hub = self.wind_speed_hub(weather_df)
  File "C:\Users\marta\PycharmProjects\Renewables\WindPowerForecast\venv\lib\site-packages\windpowerlib\modelchain.py", line 317, in wind_speed_hub
    min(range(len(weather_df['wind_speed'].columns)),
  File "C:\Users\marta\PycharmProjects\Renewables\WindPowerForecast\venv\lib\site-packages\windpowerlib\modelchain.py", line 318, in <lambda>
    key=lambda i: abs(weather_df['wind_speed'].columns[i] -
TypeError: unsupported operand type(s) for -: 'str' and 'int'

How can I solve it?

**Comment by uvchik** [comment]
We do need some more information to help you.

What version of windpowerlib do you use? From where did you get the example?

It is important that the example is compatible to your installed version. To be sure you can specify your installed version on github and download the according example. If you modified the example you should mention that and explain what you did.

**Comment by MartaFochesato** [comment]
I am using version 0.2.0 of windpowerlib and running the example modelchain_example.py taken from wind python/windpowerlib/examples/modelchain_example.py

How can I see if the example is compatible with the version that I am using?
Thank you!

**Comment by uvchik** [comment]
The version should show "v0.2.0" and NOT "dev". Open the dialog (red circle) and choose `Tags -> v0.2.0`. Then download the example. Or download https://codeload.github.com/wind-python/windpowerlib/zip/v0.2.0

![Bildschirmfoto_2020-11-18_19-38-59](https://user-images.githubusercontent.com/4760584/99573065-e3b51380-29d5-11eb-9020-ff5199d783ff.png)

**Comment by uvchik** [comment]
@MartaFochesato Please close this issue if your problems are solved.

**Comment by MartaFochesato** [comment]
Thank you a lot!

**Comment by MartaFochesato** [comment]
Dear all,

Sorry I forgot to do that, I have just closed the issue.
Thank you again for the support.

Best,

-Marta
