### ISSUE TITLE
Add readme.rst as long description on PyPi

### ISSUE THREAD

**Issue by uvchik** [wind-python/windpowerlib#13]
In the release of v0.0.5 the `README.rst` file is interpreted as long description for the [pypi page](https://pypi.python.org/pypi/windpowerlib/0.0.5). Due to changes on the pypi-page this is not the case for [v0.0.6](https://pypi.python.org/pypi/windpowerlib/0.0.6).

Have a look at the [setup.py](https://github.com/oemof/oemof/blob/dev/setup.py) file of oemof to see how we solved this issue for oemof by adding a `long_description` parameter to the `setup` call. This should automatically use the actual `README.rst` as long description on pypi if a release is uploaded. Therefore, we should fix it before the next release.

**Comment by SabineHaas** [comment]
Thank you Uwe! I added the parameter.

**Comment by uvchik** [comment]
Did you check the rendering?

```
pip install readme_renderer
python setup.py check -r -s
```

**Comment by SabineHaas** [comment]
> Did you check the rendering?
> 
> ```
> pip install readme_renderer
> python setup.py check -r -s
> ```

"The project's long description is valid RST."

However, I read [here](https://github.com/pypa/readme_renderer/issues/115) that this might not guarantee that it works. Do you know whether there is any other check?

**Comment by uvchik** [comment]
> Do you know whether there is any other check?

No. Let's hope :smile:
