### ISSUE TITLE
Connection to oedb not possible anymore.

### ISSUE THREAD

**Issue by Jalubl** [wind-python/windpowerlib#137]
If one tries to get turbine data from the oedb one gets an error like so:
ConnectionError: Database (oep) connection not successful. 
URL: https://oep.iks.cs.ovgu.de//api/v0/schema/supply/tables/wind_turbine_library/rows/?
Response: [404] 
{"detail":"Not found."}

It seems they changed their API structure or deleted data.
Does anyone know how to get new data?

**Comment by birgits** [comment]
Thanks for reporting! I reported this to the OEP developers.

**Comment by birgits** [comment]
Problem fixed! The table is back again :)
