### ISSUE TITLE
defective power key when fetching power curve

### ISSUE THREAD

**Issue by arnonuem** [wind-python/windpowerlib#17]
When running the notebook and initializing turbine enerconE126 the `fetch_curve: power_curve` parameter does not work as intended.

When in plotting section the keyword `power` is missing.
But when putting the explicit power curve of my_turbine there the power curve is plotted in the lower section.

```
enerconE126 = {
    'turbine_name': 'ENERCON E 126 7500',  # turbine name as in register
    'hub_height': 135,  # in m
    'rotor_diameter': 127,  # in m
    'fetch_curve': 'power_curve'  # fetch power curve
}
# initialise WindTurbine object
e126 = WindTurbine(**enerconE126)
```

**Comment by SabineHaas** [comment]
See #16
