### ISSUE TITLE
Add turbine 'Senvion 3.2M114' to power_curves.csv 

### ISSUE THREAD

**Issue by markuskoesler** [wind-python/windpowerlib#18]
We want to model power output for this particular turbine with windpowerlib, but its power curve isn't registered in power_curves.csv. Therefore add that.

**Comment by SabineHaas** [comment]
We added the curve. Thank you for your contribution @markuskoesler !

**Comment by markuskoesler** [comment]
Thank you too for your encouragement and quick replies.
