### ISSUE TITLE
Replace `ix` method

### ISSUE THREAD

**Issue by uvchik** [wind-python/windpowerlib#23]
We should change line 288 and 299 of the `modelchain` module to avoid these warnings and possible errors in the future.

```python
windpowerlib/modelchain.py:288: DeprecationWarning: 
  .ix is deprecated. Please use
  .loc for label based indexing or
  .iloc for positional indexing
```

**Comment by SabineHaas** [comment]
Thank you for opening the issue @uvchik ! I've fixed it.
