### ISSUE TITLE
Is display_wind_efficiency_curves a useful function?

### ISSUE THREAD

**Issue by uvchik** [wind-python/windpowerlib#26]
Is the function [display_wind_efficiency_curves()]( https://github.com/wind-python/windpowerlib/blob/aac2e3a2cee12f81764c5670cc42e4b179fac324/windpowerlib/wake_losses.py#L120) needed?

For me it is an example on how to plot wind efficiency curves, but it does not even use the internal [get_wind_efficiency_curve()](https://github.com/wind-python/windpowerlib/blob/aac2e3a2cee12f81764c5670cc42e4b179fac324/windpowerlib/wake_losses.py#L63) function.

I think we should remove this function.

If anybody thinks, that the function shows something special, we could keep the interesting part as an example.

**Comment by uvchik** [comment]
You can make one function out of two. Here is my approach #27.

**Comment by SabineHaas** [comment]
Discussion has moved to #27.
