### ISSUE TITLE
PR template is quite odd

### ISSUE THREAD

**Issue by uvchik** [wind-python/windpowerlib#29]
I think it is good to have one, but this one contains nothing then "Contributor Agreement" ([PR-Template](https://github.com/wind-python/windpowerlib/blob/dev/.github/PULL_REQUEST_TEMPLATE.md)).

https://help.github.com/articles/about-issue-and-pull-request-templates/

https://github.com/wind-python/windpowerlib/community

**Comment by SabineHaas** [comment]
Thanks for noticing!! I added something more useful.
