### ISSUE TITLE
Review of v0.0.5

### ISSUE THREAD

**Issue by uvchik** [wind-python/windpowerlib#4]
@birgits asked me to add my comments. Here they are :smile: 

1. The windpowerlib use some of pvlib's concepts. I like it because it makes it easier for energy system modellers to understand the concept. Could you therefore rename the `Modelchain` to `ModelChain`.

2. I would use the text from oemof for the Installation.
```
If you have a working Python3 environment, use pypi to install the latest oemof version.

pip install oemof

So far, the windpowerlib is mainly tested on python 3.4 but seems to work down to 2.7 
and for newer versions. Please see the installation page of the oemof documentation
for complete instructions on how to install python on your operating system.
```

3. I liked the `Basic Usage` section from the old documentation. I would at least add an "How to use the ModelChain" to the documentation.

**Comment by uvchik** [comment]
4. Could we rename `T_hub` to `temp_hub` or even `temperature_hub` because variables shouldn't be upper case.

5. There are different occurrences of `logging.info` followed by `sys.exit`. The INFO level of logging is for informations but it seems to me that we want to raise a ValueError. We could also add the given value to the error message that helps a lot if the error is caused by a typo (e.g. `baometric` instead of `barometric`).

```python

raise ValueError("'{0}' is an invalid value.".format(self.rho_model) +
                 "'rho_model' must be barometric or ideal_gas.")
```

This could lead to something like this (now the error is obvious):
```
'baometric' is an invalid value. 'rho_model' must be 'barometric' or 'ideal_gas'.
```
You could also define a default version and use logging.error without a `sys.exit()`. But the logging error might be overseen.

6. Sometimes a wrong input leads to an `sys.exit()` sometimes not. If I set the `self.density_corr` accidentally to `Fales` (instead of `False` (typo)) I will get a density correction without being noticed.

7. As I know it according to PEP8 the import statements should be place before the `__license__` variable.

**Comment by birgits** [comment]
@uvchik thank you for your comments and suggestions!
I agree with 1, 2, 4 and 6 and will change it accordingly.
As for point 3 I planned to include it again but didn't finish it in time for the release. After the openmod workshop though, I am now a big fan of the jupyter notebook and wanted to use this form as an easy entry to the windpowerlib. I know you are not a big fan, so maybe we can do both!
For point 5 I like your suggestion to raise a ValueError. We first implemented that in case of a non valid entry a default method would be used, but took it out again because I think a user input shouldn't be just overwritten.
Point 7: I followed this guideline - https://github.com/oemof/oemof/wiki/Header-and-License. Should we change the wiki entry?

**Comment by uvchik** [comment]
> I am now a big fan of the jupyter notebook and wanted to use this form as an easy entry to the windpowerlib. I know you are not a big fan, so maybe we can do both!

If I find a new project a `Basic usage` section gives me a fast impression how to use the package and if it does what I expected. Actually I do not care if it is notebook style or markdown. The `Basic usage` section does not have to include a full working example with imports etc., therefore I think markdown is the better option because a notebook implicates that it is an example rather than just an introduction.

> We first implemented that in case of a non valid entry a default method would be used, but took it out again because I think a user input shouldn't be just overwritten.

I agree. As I wrote in (6.) a misspelled parameter could lead to an unwanted and unnoticed behaviour even though a warning or logging message is displayed. Such messages can be overseen or even filtered.

> Point 7: I followed this guideline - https://github.com/oemof/oemof/wiki/Header-and-License. Should we change the wiki entry?

Sorry, my mistake. You were right: https://www.python.org/dev/peps/pep-0008/#module-level-dunder-names

**Comment by uvchik** [comment]
By the way we could use `array-like` instead of `float or array`. `array` is not defined in python while `array-like` is published by the famous numpy library and often used (https://docs.scipy.org/doc/numpy/user/basics.creation.html#converting-python-array-like-objects-to-numpy-arrays,). So array like can be a list, a Series, a numpy.array, a tuple, a float... . We could also use numpy.array but this excludes pandas.Series.

**Comment by uvchik** [comment]
`fetch_turbine_data` function:

1. The sub-function `restructure_data()` does not have a docstring nor a comment what it does (at least I did get it quickly). I think the return value is of type tuple if you return two values but I am not sure.

2. I would not mix "setting an attribute" with "returning a value". Couldn't we just return `self` and change the following lines:

```diff
- return p_nom
+ if self.nominal_power is None:
+         self.nominal_power = p_nom
+ return self
```

I hope my comments are not annoying, but I think it is important to set a standard if we want to integrate more developers.

**Comment by uvchik** [comment]
`v_wind_hellman` function

Isn't it better to use `if z_0 is not None:` instead of `try/except`. Any way the `except` expression should be restricted to a specific error. We should add the explanation to the z_0 parameter as well. "If given the  hellman_exp will be calculated, otherwise 1/7 is used" or something like this.

**Comment by birgits** [comment]
Thank you @uvchik for your revision. We implemented almost all of your suggestions and are soon ready for the next release that will include all those changes. 
The only thing left is the basic usage / notebook discussion. I set up a notebook on a new branch features/revise_example. It would be great if you and @SabineHaas could have a look at it and let me know what you think. Maybe we can elaborate the comments a bit more to make some things clearer. I would suggest to then just forward people from the documentation to the notebook for an example of how to use the windpowerlib. I would also adapt the basic_example to contain the same code to not confuse people.

**Comment by uvchik** [comment]
Notebook looks fine and you I agree that notebook and example should be the same. I had a brief look at the notebook and did not look for typos.

I added one commit and changed `array` to `array-like` in the docstrings. I use type-checkers and they were complaining about `array`.

Thank you @birgits and @SabineHaas. Windpowerlib improved a lot over the last months :smile:
Looking forward to the next release :tada:

**Comment by birgits** [comment]
@uvchik you are right, array is not quite correct (though there is a python datatype called array). What we meant to say was numpy.array. I would rather not use array-like either. As far as I could find out it is a term only used by numpy and not an official datatype. Plus we don't necessarily support lists, tuples etc. So I would change it to numpy.array. What do you say?

I revised the basic_example.py. Feedback wanted :)

**Comment by birgits** [comment]
I added the jupyter notebook to the documentation and made some changes in getting started (branch features/improve_documentation). You can have a look at [here](http://windpowerlib.readthedocs.io/en/features-improve_documentation/).

On the features/revise_example branch I added the example to the API documentation. What do you think about that?

**Comment by uvchik** [comment]
> I would rather not use array-like either. As far as I could find out it is a term only used by numpy and not an official datatype. Plus we don't necessarily support lists, tuples etc. So I would change it to numpy.array. What do you say?

I think it is more complicated as I thought at first glance. 

1. If we do not have any type casting, we could say `pandas.Series or numpy.array or float` (or anything else that allows item-wise mathematical operations). Then we have to make sure that **every** function returns a float if a float is passed and a pandas.Series if a pandas.Series is passed and so on.

2. We could also do type casting and return an numpy.array even though a list or a pandas.Series is passed to the function. In this case `array-like` would be the right expression.

The first way is nice because all input data could be a float value and we get a float in return. If we use the second way we have a greater variety of input types and a float would end up in a one item array, which is as good as a float for me.

I'm fine with both ways, but we have to make sure that all functions are consistent.

**Comment by uvchik** [comment]
> I added the jupyter notebook to the documentation and made some changes in getting started (branch features/improve_documentation). You can have a look at it here.

Looks nice. 

I did not check but I guess the example.py is exactly the same code, isn't it?

**Comment by birgits** [comment]
@uvchik I hope and think we included/considered all of your comments and will be happy about further suggestions for the latest release!
