### ISSUE TITLE
Tests fail due to failing database connection

### ISSUE THREAD

**Issue by uvchik** [wind-python/windpowerlib#41]
Tests fail due to failing database connection.

![bildschirmfoto_2019-02-04_10-08-25](https://user-images.githubusercontent.com/4760584/52198946-d82a4400-2864-11e9-80d9-93c29c83a788.png)

It is not urgent, because most of the time the connection works but we should think of mid term solution. It does not look very good, when people come to our github page:

![bildschirmfoto_2019-02-04_10-04-45](https://user-images.githubusercontent.com/4760584/52198805-576b4800-2864-11e9-8a77-d62eb1d54154.png)

For me this is connected to the question: "Is it possible to use the windpowerlib offline?"

I triggered the build process again and now everything is fine. that shows clearly that it is just a database issue.

**Comment by SabineHaas** [comment]
I definitely agree that we should add a way of saving data from the OEP to the local repository to be able to use the windpowerlib offline. 
This should be a separate issue, though, as the build of travis will still fail as the function that loads data from the database is tested.

**Comment by uvchik** [comment]
@SabineHaas Thank you for opening a new issue, I was just to lazy :blush: 

The only idea I have is to wait some time if the connection fails and try again.

**Comment by SabineHaas** [comment]
Seems like one could skip a specific test with
> @unittest.skipIf("TRAVIS" in os.environ and os.environ["TRAVIS"] == "true", "Skipping this test on Travis CI.")

https://stackoverflow.com/questions/30867145/tell-travis-to-skip-a-test-but-continue-to-include-it-in-my-main-test-suite

However, then we have to test locally as well.

**Comment by uvchik** [comment]
There are to many test that need the database that it is not an option to skip them. Otherwise have to skip most of the tests. I disconnected my computer and ran the tests. Here is the result. Yellow cross means that the test failed.

![bildschirmfoto_2019-02-05_10-10-46](https://user-images.githubusercontent.com/4760584/52263152-ada4bd80-292e-11e9-8565-63e55eb4f723.png)

**Comment by SabineHaas** [comment]
Okay good point! I don't see any other way of skipping this. 

I am planning to take care of #43 now. However, as far as I understood, at every build the CI installs the windpowerlib again and therefore would not be able to store the data offline.

One more idea: 
* Change the tests in a way that power curves are not fetched from the oedb but an example power curve is used.
* Have a separate tests for testing the calculations with power curves from oedb (like now) that will be skipped by travis. 

Advantge: builds will not fail if oedb is down
Disadvantage: calculations with power curves from oedb have to be tested locally - possible errors: format changed, ...?

**Comment by uvchik** [comment]
Once you solve #43 we will find a way to use local data for most of the test.

Anyway we should keep one database test and if it fails we cannot do anything about it besides starting it again an hour later...

But it makes thing clearer if just one test called database_test fails and not several tests, where you have to find out the reason first.

**Comment by SabineHaas** [comment]
> But it makes thing clearer if just one test called database_test fails and not several tests, where you have to find out the reason first.

I agree on that!

**Comment by SabineHaas** [comment]
> Once you solve #43 we will find a way to use local data for most of the tests.

The way it is fixed now local data is used for all tests except: 
* get_turbine_types() - will always load data from oedb
* local file does not exist at first
