### ISSUE TITLE
Bug in wind_turbine.py

### ISSUE THREAD

**Issue by GiorgioBalestrieri** [wind-python/windpowerlib#42]
Hi,

first of all it's great to see this project coming together, and to see a lot of learnings from pvlib and other projects are being leveraged.

I just started having a look at the code, and my linter is yelling at me due to [lines 340-341 of wind_turbine.py](https://github.com/wind-python/windpowerlib/blob/dev/windpowerlib/wind_turbine.py#L340-L341).

It looks like a pair of curly braces are missing:
```python
raise ConnectionError("Database connection not successful. " +
                      "Error: {}".format(result.status_code))
```

instead of
```python
raise ConnectionError("Database connection not successful. " +
                      "Error: ".format(result.status_code))
```

It's likely that the bug has not been spotted in tests because the error is only raised if the connection to the server fails.

**Comment by uvchik** [comment]
Thanks. Especially the pvlib was a good example to learn from.

You are right and the '+' is not necessary.
