### ISSUE TITLE
power output of wind farm is sum of individual turbine?

### ISSUE THREAD

**Issue by yinxiEquinor** [wind-python/windpowerlib#46]
based on the wind_farm.get_installed_power(), the power output of a wind farm is sum of individual turbine output without considering interference among turbines. Is there a more accurate method available?

def get_installed_power(self):
        r"""
        Calculates the installed power of the wind farm.
        The installed power of wind farms is necessary when a
        :class:`~.wind_turbine_cluster.WindTurbineCluster` object is used and
        it's power weighed mean hub height is calculated with
        :py:func:`~.wind_turbine_cluster.WindTurbineCluster.mean_hub_height`.
        Returns
        -------
        float
            Installed power of the wind farm.
        """
        return sum(
            wind_dict['wind_turbine'].nominal_power *
            wind_dict['number_of_turbines']
            for wind_dict in self.wind_turbine_fleet)

**Comment by SabineHaas** [comment]
Thank you for sharing your question, @yinxiEquinor!

The interference among turbines can be taken into account in two different ways in the windpowerlib. Both ways are described in more detail in the [documentation](https://windpowerlib.readthedocs.io/en/stable/model_description.html#wake-losses):

(1) **wind efficiency curves** which determine the average reduction of wind speeds within a wind farm induced by wake losses depending on the wind speed --> see [reduce_wind_speed()](https://windpowerlib.readthedocs.io/en/stable/temp/windpowerlib.wake_losses.reduce_wind_speed.html)

(2) applying wake losses to power curves by reducing the power values by a constant or on a wind speed depending **wind farm efficiency** --> see [wake_losses_to_power_curve()](https://windpowerlib.readthedocs.io/en/stable/temp/windpowerlib.power_curves.wake_losses_to_power_curve.html#windpowerlib.power_curves.wake_losses_to_power_curve)

The installed power of a wind farm instead can for example be used for calculating a power weighted mean hub height of several wind farms (turbine cluster). This is useful if you want to calculate by summing up all wind farm power curves.

**Comment by SabineHaas** [comment]
Sorry for closing the issue, I hit the wrong button;)
