### ISSUE TITLE
oemof installation

### ISSUE THREAD

**Issue by lxlsygc** [wind-python/windpowerlib#47]
**Have followed the installation procedure (Windows) step by step:**

C:\Python\WPy64-3680\scripts>pip install oemof
Requirement already satisfied: oemof in c:\python\wpy64-3680\python-3.6.8.amd64\lib\site-packages (0.2.3)
Requirement already satisfied: pyomo<5.6,>=4.4.0 in c:\python\wpy64-3680\python-3.6.8.amd64\lib\site-packages (from oemof) (5.5.1)
Requirement already satisfied: dill<=0.2.8.5 in c:\python\wpy64-3680\python-3.6.8.amd64\lib\site-packages (from oemof) (0.2.8.2)
Requirement already satisfied: networkx<2.3 in c:\python\wpy64-3680\python-3.6.8.amd64\lib\site-packages (from oemof) (2.2)
Requirement already satisfied: numpy<1.16,>=1.7.0 in c:\python\wpy64-3680\python-3.6.8.amd64\lib\site-packages (from oemof) (1.15.4)
Requirement already satisfied: pandas<0.24,>=0.18.0 in c:\python\wpy64-3680\python-3.6.8.amd64\lib\site-packages (from oemof) (0.23.4)
Requirement already satisfied: six>=1.4 in c:\python\wpy64-3680\python-3.6.8.amd64\lib\site-packages (from pyomo<5.6,>=4.4.0->oemof) (1.12.0)
Requirement already satisfied: appdirs in c:\python\wpy64-3680\python-3.6.8.amd64\lib\site-packages (from pyomo<5.6,>=4.4.0->oemof) (1.4.3)
Requirement already satisfied: PyUtilib>=5.6.3 in c:\python\wpy64-3680\python-3.6.8.amd64\lib\site-packages (from pyomo<5.6,>=4.4.0->oemof) (5.6.5)
Requirement already satisfied: ply in c:\python\wpy64-3680\python-3.6.8.amd64\lib\site-packages (from pyomo<5.6,>=4.4.0->oemof) (3.11)
Requirement already satisfied: pyreadline>=1.7.1 in c:\python\wpy64-3680\python-3.6.8.amd64\lib\site-packages (from dill<=0.2.8.5->oemof) (2.1)
Requirement already satisfied: decorator>=4.3.0 in c:\python\wpy64-3680\python-3.6.8.amd64\lib\site-packages (from networkx<2.3->oemof) (4.3.2)
Requirement already satisfied: pytz>=2011k in c:\python\wpy64-3680\python-3.6.8.amd64\lib\site-packages (from pandas<0.24,>=0.18.0->oemof) (2018.9)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\python\wpy64-3680\python-3.6.8.amd64\lib\site-packages (from pandas<0.24,>=0.18.0->oemof) (2.8.0)
Requirement already satisfied: nose in c:\python\wpy64-3680\python-3.6.8.amd64\lib\site-packages (from PyUtilib>=5.6.3->pyomo<5.6,>=4.4.0->oemof) (1.3.7)

C:\Python\WPy64-3680\scripts>

**Here is what I got after running "oemof_installation_test" :** 

*****************************
Solver installed with oemof:

cbc: not working
glpk: not working
gurobi: not working
cplex: not working

*****************************
oemof successfully installed.
*****************************

**Looks like none of them is working on my computer...**

**Comment by birgits** [comment]
As this problem only concerns the installation of the oemof package I am afraid I can't help you and would like you to open an issue at their github.

**Comment by SabineHaas** [comment]
As far as I know you have to install the solver separately, as it does not come with oemof. From your output I read that you have not installed any solver, yet.

If this doesn't solve your problem I'd also recommend you to open an issue at the oemof github.

**Comment by lxlsygc** [comment]
Dear birgits and SabineHaas, 

Thank you for your reply! I will raise this issue at the oemof github.
