### ISSUE TITLE
Release v0.2.0 (due: end of July)

### ISSUE THREAD

**Issue by birgits** [wind-python/windpowerlib#49]
The v0.2.0 will have some API changes:
- [x]  no p_nom column in power curve csv file (@SabineHaas) 
- [x]  name parameter of wind turbine, wind farm and wind turbine cluster as optional (or remove?) (@birgits) --> same for coordinates parameter?!
- [x]  remove power_output attribute from wind turbine, wind farm and wind turbine cluster (@birgits)
- [x]  remove installed_power attribute (@birgits )
- [x] use efficiency attribute for wake_losses_to_power_curve() instead of wake_losses_model parameter (@SabineHaas)
- [x] remove overwrite parameter from wind_turbine.get_turbine_data_from_oedb() (@SabineHaas)
- [x] remove deprecation warnings (@SabineHaas and @birgits)
- [x] remove fetch_curve and data_source parameters from WindTurbine (@SabineHaas)
- [x] adapt examples (@birgits)
- [x]  check if tests are adapted, f.e. no fetch_curve parameter (@SabineHaas)
- [x]  csv file containing all turbine data from oedb apart from curves (@SabineHaas)
- [x] Check if example/modelchain_example.ipynb was merged correctly (@birgits)
- [x] document changes in whats new (@SabineHaas, @birgits)

**Comment by uvchik** [comment]
Thanks to @SabineHaas it is possible to use the windpowerlib offline but for the next major release I would suggest to restructure the API.

As there has been some communication problems in the last month I would suggest to make a breakout group at the next oemof meeting.

**Comment by birgits** [comment]
> Thanks to @SabineHaas it is possible to use the windpowerlib offline but for the next major release I would suggest to restructure the API.

@uvchik can you specify this a bit more? Because if you have the csv vs hdf5 discussion in mind, we are planning to go back to csv in the next [release](https://githu b.com/wind-python/windpowerlib/issues/48) and should therefore talk about this soon (this or the upcoming week). If it's something that can wait until the dev meeting a breakout group sounds good.

**Comment by uvchik** [comment]
No, it is more about the whole data-base-file-structure. But I really appreciate the change back to csv.

**Comment by uvchik** [comment]
PR #62 includes my ideas from above.
