### ISSUE TITLE
Data of power and power coefficient curves

### ISSUE THREAD

**Issue by birgits** [wind-python/windpowerlib#5]
The data we right now provide along with the windpowerlib lacks references and a license and should therefore be replaced.  Possible alternatives for wind turbine databases are:
* https://sam.nrel.gov/libraries
* http://www.wind-power-program.com/download.htm

**Comment by SabineHaas** [comment]
Solved with pull request #31.
The power (coefficient) curves are now fetched from the [Open Energy Database](https://openenergy-platform.org/dataedit/) (oedb). The option of loading own data from a csv file stays.
