### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by birgits** [wind-python/windpowerlib#57]
This issue collects possible/necessary improvements to the documentation and examples:
* [x] document models in modelchains, e.g. explain or link to explanation of what different [wind_speed_models](https://github.com/wind-python/windpowerlib/blob/dev/windpowerlib/modelchain.py#L24) do (modelchain @birgits, cluster modelchain @SabineHaas)
* [x] add axes labels to power output plots

**Comment by SabineHaas** [comment]
See PR #64
