### ISSUE TITLE
Update release wiki and switch to twine

### ISSUE THREAD

**Issue by SabineHaas** [wind-python/windpowerlib#59]
WARNING: Uploading via this command is deprecated, use twine to upload instead (https://pypi.org/p/twine/)

**Comment by birgits** [comment]
I updated the wiki and will check if everything works as documented with the next release.

**Comment by uvchik** [comment]
Worked fine with the v0.1.3 release :-)

**Comment by uvchik** [comment]
May we close it, as the v0.2.0 release has been done successfully?
