### ISSUE TITLE
New class WindTurbineGroup

### ISSUE THREAD

**Issue by birgits** [wind-python/windpowerlib#65]
In PR #63 @uvchik suggested an additional class WindTurbineGroup in order to have a cleaner initialization of the WindFarm class. As that PR was intended to allow specifying a WindFarm with a total installed capacity per turbine type and the discussion about this new class went beyond that topic, I decided to move it to a new issue. Important comments about the new class from the PR are:
https://github.com/wind-python/windpowerlib/pull/63#issuecomment-517251617
https://github.com/wind-python/windpowerlib/pull/63#issuecomment-517624171

**Comment by uvchik** [comment]
Addressed by #68.
