### ISSUE TITLE
logging.info messag should be an error

### ISSUE THREAD

**Issue by uvchik** [wind-python/windpowerlib#69]
In the wind_farm module [line 399ff](https://github.com/wind-python/windpowerlib/blob/dev/windpowerlib/wind_farm.py#L399) a logging message is shown if the wake_loss model 'wind_farm_efficiency' is chosen but no efficiency is given.

In my opinion an exception should be raised because the efficiency is mandatory to calculate the wake_losses. I think it is error prone to ignore it and to just show a logging info message.

**Comment by birgits** [comment]
@uvchik I agree. I am not sure though if there is a reason why @SabineHaas implemented it like that. Do you think we can wait until her return or do you necessarily want it in the v0.2.0 release?

**Comment by uvchik** [comment]
I think it is okay for v0.2.1 if manage to release the v0.2.0 soon :smirk:

**Comment by SabineHaas** [comment]
I remember implementing it like this to not break longer simulations. But I agree that it should at least be a warning. I also wouldn't oppose to an error.

**Comment by uvchik** [comment]
> I remember implementing it like this to not break longer simulations.

Following this argumentation we have to remove all errors. I think people should take care on there own e.g. by using try/except in there main script.

> But I agree that it should at least be a warning. I also wouldn't oppose to an error.

Does it make sense to use the `wind_farm_efficiency` method without a valid efficiency?
- Yes that's fine -> nothing
- Yes, in some very special cases -> warning
- No, it does not make sense -> error

Do we have to catch the wrong behaviour later on?
- Yes because `power * efficiency` does not work if efficiency is None -> error
- No, that's fine -> warning or nothing (depends on the first question)

**Comment by SabineHaas** [comment]
oemof dev decision:
logging message will be changed into error message.
Add info in docstring: if wake_losses_model is 'wind_farm_efficiency' efficiency is needed.

**Comment by SabineHaas** [comment]
solved with PR #87
