### ISSUE TITLE
Not able to install windpowerlib in anaconda spyder

### ISSUE THREAD

**Issue by sandeepbando** [wind-python/windpowerlib#7]
Hi,
I am using Anaconda Spyder(python 3.6). I am not at all being able to install the windpowerlib into my system.Could you please help me in that.
Thanks,
Sandeep

**Comment by birgits** [comment]
Hi Sandeep, could you please specify your problem? Are you doing a 'pip install windpowerlib' inside your anaconda environment? If so, what error message do you get?

**Comment by birgits** [comment]
@sandeepbando were you able to solve your installation problem?
