### ISSUE TITLE
Oedb connection not successful

### ISSUE THREAD

**Issue by mark95** [wind-python/windpowerlib#71]
When i run df = wt.get_turbine_types(print_out=False), from the example 
i get ConnectionError: Database connection not successful. Response: [404].
I hit the URL with curl and got:
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://openenergy-platform.org/api/v0/schema/supply/tables/turbine_library/rows/?">here</a>.</p>

**Comment by uvchik** [comment]
Thank you @mark95 for reporting this bug.

It would be helpful to tell which version you use but I guess it is v0.1.2.

**Comment by uvchik** [comment]
I can confirm this bug for v0.1.2.

**Comment by uvchik** [comment]
I fixed this bug in PR #72.

**Comment by uvchik** [comment]
Fix was released with [v0.1.3](https://github.com/wind-python/windpowerlib/releases/tag/v0.1.3).

**Comment by birgits** [comment]
Danke schön!!

________________________________
Von: Uwe Krien <notifications@github.com>
Gesendet: Montag, 2. September 2019 17:25
An: wind-python/windpowerlib
Cc: Birgit Schachler; Assign
Betreff: Re: [wind-python/windpowerlib] Oedb connection not successful (#71)


Fix was released with v0.1.3<https://github.com/wind-python/windpowerlib/releases/tag/v0.1.3>.

-
