### ISSUE TITLE
Change license to a permissive licence

### ISSUE THREAD

**Issue by uvchik** [wind-python/windpowerlib#76]
The windpowerlib is a basic library that should be used in other libraries. The GPL3 makes it more complicate to use it in projects with permissive licenses such as BSD, MIT, Apache...

Therefore, I would like to change the license to a more permissive license.

The easy MIT licences could be a good choice.

**Comment by uvchik** [comment]
I started the same discussion in [oemof/organisation](https://github.com/oemof/organisation/issues/50). We can discuss it there for the whole framework and follow the decission if no one objects.

**Comment by SabineHaas** [comment]
I have merged your PR #77 - thank you!
