### ISSUE TITLE
Use the wind_turbine module after importing the whole windpowerlib

### ISSUE THREAD

**Issue by uvchik** [wind-python/windpowerlib#8]
At the moment it is not possible to use the `wind_turbine` module after importing the whole windpowerlib package. Is it intended to work like this or is it a bug? I think this behaviour is not very convenient.

```python
import windpowerlib
turbine = {...}
windpowerlib.wind_turbine.WindTurbine(**turbine)
```
The code above raises an error but I think it should not.

```AttributeError: module 'windpowerlib' has no attribute 'wind_turbine'```

**Comment by birgits** [comment]
Sorry for that! I fixed the imports in the master branch. I also added your suggestions to directly import ModelChain and WindTurbine. You can now import them via `from windpowerlib import WindTurbine`.

**Comment by uvchik** [comment]
Thanks a lot, works great now and the shortcut looks very clear in the code.

```python
import windpowerlib
turbine = {...}
wpp = windpowerlib.WindTurbine(**turbine)
mc = windpowerlib.ModelChain(wpp, **modelchain_data)
mc.run_model(weather_data)
```
