### ISSUE TITLE
Simplify the way to use weather data with the windpowerlib

### ISSUE THREAD

**Issue by uvchik** [wind-python/windpowerlib#80]
The weather data set for the windpowerlib has to have a very specific format. At the moment one has to pass a MultiIndex DataFrame with specific names and the data heights in the second level.

The format is useful but it seems to be a barrier for some users to convert their own weather data to this format.

This is a reminder, for the windpowerlib session at the oemof developer meeting in December (https://oemof.org/news/).

**Comment by birgits** [comment]
I'll close this issue as this is already addressed in #9 and set #9 milestone to the developer meeting.
