### ISSUE TITLE
Creating unphysical instances of WindTurbine class

### ISSUE THREAD

**Issue by vezeli** [wind-python/windpowerlib#89]
With the current API nothing prevents a user from creating a nonphysical wind turbine instance, i.e., wind turbine that has *hub_height* shorter than 0.5*_rotor_diameter_. I would suggest raising ```ValueError``` with a useful message in case this happens, what do you think?

I wrote a small fix that passes all the existing test and adds new. If this is something you would like to review, and see fixed, I could easily put it in a PR?

**Comment by uvchik** [comment]
Go ahead. Thank you.
