### ISSUE TITLE
NaN's in weather_df will result in only zero's as power_output

### ISSUE THREAD

**Issue by woutertP1** [wind-python/windpowerlib#95]
Running latest version (0.2.0 on MacOS).

When I calculate the power output and I insert a weather_df with NaN's I will only receive zero's as power_output. There's no mention of NaN's using logging level on Debug. It took me a bit of time to find out that NaN's in the weather_df were the cause of this issue.

Proposed resolution:
- Add warning level when processing the weather_df
- Or reject the weather_df input when NaN's are present

**Comment by uvchik** [comment]
We could provide a WindpowerlibUserWarning -> #96
